import "./globals.css";

import Header from "./header";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <script
          async
          src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.js"
        ></script>
        <script
          async
          src="https://publications.gc.ca/boew-wet/wet4.0ca/wet-boew/js/wet-boew.min.js"
        ></script>
      </head>

      <body className={inter.className}>
        <Header></Header>
        <main> {children}</main>
      </body>
    </html>
  );
}
